[book]
title = "Asynchronous Programming in Rust"
authors = ["Taylor Cramer"]

src = "src-kr"

[build]
create-missing = false

[preprocess.links]

[output.html]
git-repository-url = "https://github.com/rust-lang/async-book"
site-url = "/async-book/"

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
